# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  name: storage
spec:
  replicas: 1
  selector:
    # labels the pods
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: crm
        name: storage
    spec:
      containers:
        # The container name to execute pods
        - name: storage
          image: "11112003/crm-storage:master"
          volumeMounts:
            - name: file
              mountPath: /usr/app/files
          envFrom:
            - configMapRef:
                name: "crm-env"
          ports:
            # Assign ports to expose container
            - containerPort: 3000 # Node port
            - containerPort: 5000 # Grpc port
          imagePullPolicy: Always
          # resources:
          #   limits:
          #     memory: "1Gi"
          #     cpu: "0.25"
      volumes:
        - name: file
          persistentVolumeClaim:
            claimName: storage-claim
