apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: storage-nodeport
  labels:
    app: crm
spec:
  type: NodePort
  # Choose how to expose your service
  ports:
    # The port number to expose the service
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30020
      name: http
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30021
      name: grpc

  # Pod to route service traffic
  selector:
    app: crm
    name: storage
