apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: crm-env
  labels:
    app: crm
data:
  # NODEJS
  NODE_ENV: production
  # Database
  GORM_DSN: "host=postgres user=crm-manager password=strong#password dbname=crm-dev port=5432"
  PG_USER: crm-manager
  PG_PASSWORD: "strong#password"
  PG_HOST: postgres
  PG_DATABASE: crm-dev
  PG_PORT: "5432"
  # Common
  DEFAULT_AVATAR: "https://friendify-backup.s3.ap-southeast-1.amazonaws.com/avatars/default.png"
  #Jwt
  JWT_SECRECT: "123123123"
  # Redis config
  REDIS_URL: "redis:6379"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  # Queue config
  AMQP_LINK: "amqp://user:password@rabbitmq:5672/"
  AMPQ_LINK: "amqp://user:password@rabbitmq:5672/"
  CHANNEL_REQUIRES: "notification,mail,user_registered"
  # Role config
  USER_ISS: "user_good"
  SUPER_ADMIN_ROLE: Root
  DEFAULT_ROLE_ID: "2"
  # Up stream
  Authentication: http://authentication-service:8080/api/v1
  Plugin: http://plugins-service:3000/api/v1
  Mail: http://mail-service:3000/api/v1
  sales: http://sale-service:3000/api/v1
  customers: http://customer-service:3000/api/v1
  Tag: http://tag-service:3000/api/v1
  # Grpc
  EVENT_GRPC: event-gateway:5000
  STORAGE_GRPC: storage-service:50051
  Product: http://products-service:3000/api/v1
  GOONG_MAP_API_KEY: b2BHdFHIpa58n6uj3McKOAgBEoKC6wvs51FuxwRj
  # Github branch
  BRANCHES.development: dev
  BRANCHES.production: master
  # Mattermost
  MATTERMOST_WEB_HOOK: https://mattermost.relationc.com/hooks/wf4fogqq8ib5zx61dd9oe7hifc
  # Minio
  MINIO_ENDPOINT: s3.relationc.com
  MINIO_PORT: "443"
  MINIO_ACCESS_KEY: P6lE1v297N41fOab3MHX
  MINIO_SECRET_KEY: 5ssNg5WmxBupeY9iYGF1TamGA7cvGfVTaJtR1sU5
  PRODUCT_IMAGE_PREFIX: https://s3.relationc.com/crm/images/products/
