# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  name: event
spec:
  replicas: 1
  selector:
    # labels the pods
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: crm
        name: event
    spec:
      containers:
        # The container name to execute pods
        - name: event
          image: "11112003/crm-event:master"
          envFrom:
            - configMapRef:
                name: "crm-env"
          ports:
            # Assign ports to expose container
            - containerPort: 3000
          imagePullPolicy: Always
          # resources:
          #   limits:
          #     memory: "1Gi"
          #     cpu: "0.25"
