apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: authentication-service
  labels:
    app: crm
spec:
  # Choose how to expose your service
  ports:
    # The port number to expose the service
    - protocol: TCP
      port: 8080

  # Pod to route service traffic
  selector:
    app: crm
    name: authentication-service
