apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: "single-node"
            - name: discovery.seed_hosts
              value: "0.0.0.0"
            # - name: xpack.security.http.ssl.enabled
            #   value: "false"
            - name: ELASTIC_USERNAME
              value: "elastic"
            - name: ELASTIC_PASSWORD
              value: "hX8veOCNwLOIqC9fkyfa"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      nodePort: 30034
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: elasticsearch
#   labels:
#     name: elasticsearch
#   annotations:
#     cert-manager.io/issuer: "crm-issuer"
#     traefik.ingress.kubernetes.io/router.tls: "true"
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
# spec:
#   tls:
#     - hosts:
#         - es.relationc.com:8200
#       secretName: elasticsearch-ssl
#   rules:
#     - host: es.relationc.com:8200
#       http:
#         paths:
#           - pathType: Prefix
#             path: "/"
#             backend:
#               service:
#                 name: elasticsearch
#                 port:
#                   number: 9200
