apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-database
spec:
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
        name: database
    spec:
      containers:
        - name: mattermost-database
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: mattermost-config
      volumes:
        - name: db-data
          persistentVolumeClaim:
            # reference the PersistentVolumeClaim
            claimName: mattermost-database
---
apiVersion: v1
kind: Service
metadata:
  name: mattermost-database
spec:
  selector:
    app: mattermost
    name: database
  ports:
    - port: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mattermost-database
spec:
  storageClassName: manual
  capacity:
    # PV Storage capacity
    storage: 5Gi
  # A db can write and read from volumes to multiple pods
  accessModes:
    - ReadWriteMany
  # Specify the path to persistent the volumes
  hostPath:
    path: "/mattermost/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-database
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
