apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: db-secret-credentials
  namespace: friendify
  labels:
    app: postgresdb
data:
  # User DB
  POSTGRES_DB: crm-dev
  # Db user
  POSTGRES_USER: crm-manager
  # Db password
  POSTGRES_PASSWORD: strong#password
